# -*- coding: utf-8 -*-
"""Q1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10WbU_C9EBnTzV6cJ4UfRlOMDFwR7GGMc
"""

import csv

class Film:
    def __init__(self,title,year,runtime):
      self.title = title
      self.year = year
      self.runtime = runtime

    def getTitle(self):
      return self.title


    def getYear(self):
        return self.year
    
    def getRuntime(self):
        return self.runtime

class Films:
    def __init__(self,File,L):
      self.File = File
      self.L = L
    
    def readFile(self):
      for i in self.File:
        print(i)

    def createFilmsList(self):
      for i in self.File:
        (self.L).append([i[1],i[2],i[4]])

    def getFilmsList(self):
      return self.L

fname = open("imdb_top_1000.csv")
reader = csv.reader(fname)
Head = []
Head = next(reader)
l =[]


f = Films(reader,l)
#f.readFile()
C = f.createFilmsList()

G = f.getFilmsList()

print("FILMS RELEASED AFTER 2019:")
for i in G:
  if i[1]>'2019':
    print(i[0], "was released in", i[1], "and has a runtime of", i[2])

print("\n")
print("FILMS HAVING RUNTIME LESS THAN 70 MINUTES:")
for i in G:
  if i[2]>'321 min' and i[2]<'70 min':
    print(i[0], "was released in", i[1], "and has a runtime of", i[2])



fname.close()
